//! The goethite control-plane REST API.
//!
//! Serves `/api/v1` with axum and describes it with an OpenAPI document
//! generated by utoipa. The API binds to loopback until an admin token is
//! configured, and every configuration change is audit-logged.
//!
//! Status: empty skeleton. The API arrives in Phase 2.
