//! The goethite control-plane REST API.
//!
//! Serves `/api/v1` with axum and describes it with an OpenAPI document
//! generated by utoipa ([`openapi`]). Every change goes through the store,
//! which validates it and writes an audit entry, and is then applied to the
//! data plane through [`Control`], which the binary implements.
//!
//! Access: with an admin token configured (only its SHA-256 hash, see
//! [`hash_token`]), every request except `/api/v1/health` needs
//! `Authorization: Bearer <token>`; without one, only loopback clients are
//! answered. Requests a browser could be tricked into sending (DNS
//! rebinding, cross-site requests) are refused. Responses carry a strict
//! Content Security Policy and API answers are never cached; request bodies
//! are limited to 1 MiB and requests to 30 seconds.
//!
//! The same listener serves the web UI ([`WebAssets`]) for every other path.

mod auth;
mod error;
mod handlers;
mod openapi;
mod serve;
mod web;

use std::future::Future;
use std::pin::Pin;
use std::sync::Arc;
use std::time::{Duration, SystemTime};

use axum::Router;
use axum::extract::DefaultBodyLimit;
use axum::http::header::{
    CACHE_CONTROL, CONTENT_SECURITY_POLICY, REFERRER_POLICY, X_CONTENT_TYPE_OPTIONS,
    X_FRAME_OPTIONS,
};
use axum::http::{HeaderValue, Request};
use axum::middleware::{self, Next};
use axum::response::Response;
use goethite_store::{QueryLog, Store};
use jiff::Timestamp;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

pub use auth::{PeerAddr, TOKEN_PREFIX, TokenHash, TokenHashError, generate_token, hash_token};
pub use error::{ApiError, ErrorBody, ErrorDetail};
pub use openapi::{openapi, openapi_json};
pub use serve::{ApiListeners, MAX_CONNECTIONS, Serving, serve, serve_router};
pub use web::{EmbeddedWeb, WebAssets};

/// The checks made on every request's `Host`, `Origin` and path, for the
/// fuzz targets. Not a stable API.
#[doc(hidden)]
pub mod fuzzing {
    pub use crate::auth::{is_loopback_authority, origin_authority};
    pub use crate::web::is_plain;
}

/// The largest request body accepted.
pub const MAX_BODY: usize = 1024 * 1024;

/// API settings.
#[derive(Clone, Debug, Default)]
pub struct ApiConfig {
    /// The admin token's hash; without one, only loopback is answered.
    pub token: Option<TokenHash>,
    /// HTTPS settings; plain HTTP without them.
    pub tls: Option<Arc<rustls::ServerConfig>>,
    /// The web UI's files; no web UI without them.
    pub web: Option<Arc<dyn WebAssets>>,
}

/// What changed in the store, so the data plane knows what to recompile.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Change {
    /// Lists or custom rules: the filter must be recompiled.
    Filter,
    /// Groups, clients, schedules or settings: only the policy.
    Policy,
}

/// A boxed future, for the object-safe [`Control`] trait.
pub type BoxFuture<'a> = Pin<Box<dyn Future<Output = ()> + Send + 'a>>;

/// The data plane, as the API sees it. The binary implements this.
pub trait Control: Send + Sync + 'static {
    /// How the node is doing.
    fn status(&self) -> Status;
    /// Applies a store change; resolves once queries use it.
    fn apply(&self, change: Change) -> BoxFuture<'_>;
    /// Downloads the filter lists now.
    fn refresh_lists(&self);
    /// Pauses filtering until `until`, or resumes it with `None`.
    fn pause(&self, until: Option<SystemTime>);
    /// Until when filtering is paused, if it is.
    fn paused_until(&self) -> Option<SystemTime>;
    /// The metrics in the Prometheus text format.
    fn metrics(&self) -> String;
}

/// How the node is doing.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct Status {
    /// The running version.
    pub version: String,
    /// When goethite started.
    pub started_at: Timestamp,
    /// Whether filtering is on in the settings.
    pub protection: bool,
    /// Until when filtering is paused, if it is.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub paused_until: Option<Timestamp>,
    /// The compiled filter.
    pub filter: FilterStatus,
    /// Each list, by ID.
    pub lists: Vec<ListStatus>,
    /// The upstreams, in configured order.
    pub upstreams: Vec<UpstreamStatus>,
    /// The cache, if there is one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cache: Option<CacheStatus>,
    /// The query log.
    pub query_log: QueryLogStatus,
}

/// The compiled filter.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct FilterStatus {
    /// Rules compiled in.
    pub rules: u64,
    /// Bytes of memory the rules take.
    pub memory_bytes: u64,
}

/// One list.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct ListStatus {
    /// The list's ID.
    pub id: String,
    /// Rules read from it, if it was read.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rules: Option<u64>,
    /// Lines with syntax goethite does not support yet.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub unsupported: Option<u64>,
    /// Lines that are not valid rules.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub invalid: Option<u64>,
    /// Why it could not be read, if it could not.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    /// When a download was last tried.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_attempt: Option<Timestamp>,
    /// When a download last succeeded or found the list unchanged.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_success: Option<Timestamp>,
    /// Why the last download failed, if it did.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub download_error: Option<String>,
}

/// One upstream.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct UpstreamStatus {
    /// Address and port.
    pub address: String,
    /// `udp`, `tcp`, `tls` or `https`.
    pub protocol: String,
    /// False while it is skipped after repeated failures.
    pub healthy: bool,
    /// Failures since it last answered.
    pub consecutive_failures: u32,
}

/// The cache.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct CacheStatus {
    /// Answers in it.
    pub entries: u64,
    /// Lookups answered from it.
    pub hits: u64,
    /// Lookups that were not.
    pub misses: u64,
}

/// The query log.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct QueryLogStatus {
    /// Whether queries are logged.
    pub enabled: bool,
    /// Entries in it.
    pub entries: u64,
    /// Entries dropped because the writer could not keep up.
    pub dropped: u64,
}

/// Everything the handlers share.
pub struct Api {
    /// The store.
    pub store: Arc<Store>,
    /// The query log and statistics.
    pub log: Arc<QueryLog>,
    /// The data plane.
    pub control: Arc<dyn Control>,
    /// Settings.
    pub config: ApiConfig,
}

/// How long one request may take.
const REQUEST_TIMEOUT: Duration = Duration::from_secs(30);

/// The routes, with authentication, limits and security headers.
pub fn router(api: &Arc<Api>) -> Router {
    let protected = handlers::routes().route_layer(middleware::from_fn_with_state(
        Arc::clone(api),
        auth::authenticate,
    ));
    Router::new()
        .route("/api/v1/health", axum::routing::get(handlers::health))
        .merge(protected)
        .fallback(web::serve)
        .with_state(Arc::clone(api))
        .layer(DefaultBodyLimit::max(MAX_BODY))
        .layer(middleware::from_fn_with_state(Arc::clone(api), auth::guard))
        .layer(middleware::from_fn(limit_time))
        .layer(middleware::from_fn(security_headers))
}

/// Gives up on requests that take too long.
async fn limit_time(request: Request<axum::body::Body>, next: Next) -> Result<Response, ApiError> {
    tokio::time::timeout(REQUEST_TIMEOUT, next.run(request))
        .await
        .map_err(|_| ApiError::internal("the request took too long"))
}

/// Headers every response gets: a strict Content Security Policy, and no
/// framing, sniffing or referrers. Responses are not cached unless they say
/// otherwise (only the web UI's files do).
async fn security_headers(request: Request<axum::body::Body>, next: Next) -> Response {
    let mut response = next.run(request).await;
    let headers = response.headers_mut();
    for (name, value) in [
        (
            CONTENT_SECURITY_POLICY,
            "default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; \
             font-src 'self'; connect-src 'self'; object-src 'none'; base-uri 'none'; \
             form-action 'self'; frame-ancestors 'none'",
        ),
        (X_CONTENT_TYPE_OPTIONS, "nosniff"),
        (X_FRAME_OPTIONS, "DENY"),
        (REFERRER_POLICY, "no-referrer"),
    ] {
        headers.insert(name, HeaderValue::from_static(value));
    }
    headers
        .entry(CACHE_CONTROL)
        .or_insert(HeaderValue::from_static("no-store"));
    response
}
