//! The goethite control-plane REST API.
//!
//! Serves `/api/v1` with axum and describes it with an OpenAPI document
//! generated by utoipa ([`openapi`]). Every change goes through the store,
//! which validates it and writes an audit entry, and is then applied to the
//! data plane through [`Control`], which the binary implements.
//!
//! Access: with an admin token configured (only its SHA-256 hash, see
//! [`hash_token`]), every request except `/api/v1/health` needs
//! `Authorization: Bearer <token>`; without one, only loopback clients are
//! answered. Requests a browser could be tricked into sending (DNS
//! rebinding, cross-site requests) are refused. Responses carry a strict
//! Content Security Policy and API answers are never cached; request bodies
//! are limited to 1 MiB and requests to 30 seconds.
//!
//! The same listener serves the web UI ([`WebAssets`]) for every other path.

#![forbid(unsafe_code)]

mod auth;
pub mod catalog;
mod cluster;
mod docs;
mod error;
mod handlers;
pub mod leak;
mod login_attempts;
mod openapi;
mod passwords;
pub mod recommended;
mod serve;
pub mod services;
mod sessions;
mod totp;
mod update;
mod users;
mod web;

use std::future::Future;
use std::pin::Pin;
use std::sync::Arc;
use std::time::{Duration, SystemTime};

use axum::Router;
use axum::extract::DefaultBodyLimit;
use axum::http::header::{
    CACHE_CONTROL, CONTENT_SECURITY_POLICY, REFERRER_POLICY, X_CONTENT_TYPE_OPTIONS,
    X_FRAME_OPTIONS,
};
use axum::http::{HeaderValue, Request};
use axum::middleware::{self, Next};
use axum::response::Response;
use goethite_store::{Actor, QueryLog, StatsReport, Store};
use jiff::Timestamp;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

pub use auth::{PeerAddr, TOKEN_PREFIX, TokenHash, TokenHashError, generate_token, hash_token};
pub use cluster::{
    ClusterRole, ClusterStatus, Forwarded, ForwardedAnswer, MemberState, MemberStatus, Membership,
    PeerStatus, RoleChange, SyncStatus, Writes, execute,
};
pub use docs::{EmbeddedDocs, SCALAR as DOCS_SCALAR};
pub use error::{ApiError, ErrorBody, ErrorDetail};
pub use openapi::{openapi, openapi_json};
pub use passwords::{PasswordError, check_new, hash_password, new_password, verify_password};
pub use serve::{
    ApiListeners, HANDSHAKE_TIMEOUT, MAX_CONNECTIONS, MAX_CONNECTIONS_PER_PEER, PeerCertificate,
    Serving, serve, serve_router,
};
pub use totp::{
    code as totp_code, decode_secret as decode_totp_secret, encode_secret as encode_totp_secret,
    hash_recovery_code,
};
pub use update::UpdateCheck;
pub use web::{EmbeddedWeb, WebAssets};

/// The checks made on every request's `Host`, `Origin` and path, for the
/// fuzz targets. Not a stable API.
#[doc(hidden)]
pub mod fuzzing {
    pub use crate::auth::{is_loopback_authority, origin_authority};
    pub use crate::web::is_plain;
}

/// The largest request body accepted.
pub const MAX_BODY: usize = 1024 * 1024;

/// API settings.
#[derive(Clone, Debug, Default)]
pub struct ApiConfig {
    /// The admin token's hash; without one, only loopback is answered.
    pub token: Option<TokenHash>,
    /// HTTPS settings; plain HTTP without them.
    pub tls: Option<Arc<rustls::ServerConfig>>,
    /// The web UI's files; no web UI without them.
    pub web: Option<Arc<dyn WebAssets>>,
    /// The API reference's files (see [`EmbeddedDocs`]): served at
    /// `/api/docs` to loopback clients only. Off without them.
    pub docs: Option<Arc<dyn WebAssets>>,
}

/// What changed in the store, so the data plane knows what to recompile.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Change {
    /// Filter lists: the filter must be recompiled, and the lists fetched
    /// now rather than at the next scheduled refresh.
    Lists,
    /// Custom rules: the filter must be recompiled.
    Filter,
    /// Groups, clients, schedules, local records or settings: only the
    /// policy.
    Policy,
}

/// A boxed future, for the object-safe [`Control`] trait.
pub type BoxFuture<'a> = Pin<Box<dyn Future<Output = ()> + Send + 'a>>;

/// A boxed future with a result, for the object-safe [`Control`] trait.
pub type BoxResult<'a, T> = Pin<Box<dyn Future<Output = Result<T, ApiError>> + Send + 'a>>;

/// The data plane, as the API sees it. The binary implements this.
pub trait Control: Send + Sync + 'static {
    /// How the node is doing.
    fn status(&self) -> Status;
    /// Applies a store change; resolves once queries use it.
    fn apply(&self, change: Change) -> BoxFuture<'_>;
    /// Downloads the filter lists now.
    fn refresh_lists(&self);
    /// Pauses filtering until `until`, or resumes it with `None`.
    fn pause(&self, until: Option<SystemTime>);
    /// Until when filtering is paused, if it is.
    fn paused_until(&self) -> Option<SystemTime>;
    /// The metrics in the Prometheus text format.
    fn metrics(&self) -> String;

    /// Checks the project's releases for a newer goethite.
    ///
    /// # Errors
    ///
    /// When the check cannot be made.
    fn check_update(&self) -> BoxResult<'_, UpdateCheck> {
        Box::pin(async {
            Err(ApiError::unavailable(
                "this node does not check for updates",
            ))
        })
    }

    /// This node's cluster, if it is in one.
    fn cluster(&self) -> Option<ClusterStatus> {
        None
    }

    /// The FilterLists directory, as far as goethite can use it.
    fn directory(&self) -> BoxResult<'_, catalog::Directory> {
        Box::pin(async { Err(directory_off()) })
    }

    /// A list's details from the FilterLists directory.
    fn directory_list(&self, id: u64) -> BoxResult<'_, catalog::DirectoryList> {
        let _ = id;
        Box::pin(async { Err(directory_off()) })
    }

    /// How big the recommended lists say they are.
    fn recommended_sizes(&self) -> BoxResult<'_, recommended::RecommendedSizes> {
        Box::pin(async { Err(directory_off()) })
    }

    /// The services groups can block.
    ///
    /// # Errors
    ///
    /// [`services_off`] when this node does not use the catalog.
    fn services(&self) -> Result<services::Services, ApiError> {
        Err(services_off())
    }

    /// This node's DNS leak tests.
    ///
    /// # Errors
    ///
    /// When this node does not run them.
    fn leak_tests(&self) -> Result<&leak::LeakTests, ApiError> {
        Err(ApiError::unavailable(
            "this node does not run DNS leak tests",
        ))
    }

    /// Where configuration changes made through this node go.
    fn writes(&self) -> Writes {
        Writes::Local
    }

    /// Sends a configuration change to the cluster's leader.
    fn forward(&self, forwarded: Forwarded) -> BoxResult<'_, ForwardedAnswer> {
        let _ = forwarded;
        Box::pin(async { Err(ApiError::not_found("this node is not in a cluster")) })
    }

    /// The other members' statistics for the last `hours` hours, with long
    /// top lists for merging; witnesses have none.
    fn member_stats(&self, hours: u32) -> BoxResult<'_, Vec<MemberStats>> {
        let _ = hours;
        Box::pin(async { Ok(Vec::new()) })
    }

    /// Removes a member from the cluster; this node leads it.
    fn remove_member(&self, node: String, actor: Actor) -> BoxResult<'_, ClusterStatus> {
        let _ = (node, actor);
        Box::pin(async { Err(ApiError::not_found("this node is not in a cluster")) })
    }

    /// Takes the cluster over (`Primary`), or leaves it to join another
    /// (`Replica`).
    fn set_role(
        &self,
        role: ClusterRole,
        force: bool,
        actor: Actor,
    ) -> BoxResult<'_, ClusterStatus> {
        let _ = (role, force, actor);
        Box::pin(async { Err(ApiError::not_found("this node is not in a cluster")) })
    }
}

/// Another member's statistics, or why they could not be had.
#[derive(Clone, Debug)]
pub struct MemberStats {
    /// The member.
    pub node: String,
    /// Its statistics.
    pub stats: Result<StatsReport, String>,
}

/// The answer when this node does not use the FilterLists directory.
pub fn directory_off() -> ApiError {
    ApiError::unavailable(
        "looking lists up is turned off on this node ([filter] directory in its config file)",
    )
}

/// The answer when this node does not use the services catalog.
pub fn services_off() -> ApiError {
    ApiError::unavailable(
        "blocked services are turned off on this node ([filter] services in its config file)",
    )
}

/// How the node is doing.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct Status {
    /// The running version.
    pub version: String,
    /// When goethite started.
    pub started_at: Timestamp,
    /// Whether filtering is on in the settings.
    pub protection: bool,
    /// Until when filtering is paused, if it is.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub paused_until: Option<Timestamp>,
    /// The compiled filter.
    pub filter: FilterStatus,
    /// Each list, by ID.
    pub lists: Vec<ListStatus>,
    /// The upstreams, in configured order; none with recursion.
    pub upstreams: Vec<UpstreamStatus>,
    /// Recursive resolution, when it is on instead of upstreams.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub recursion: Option<RecursionStatus>,
    /// The cache, if there is one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cache: Option<CacheStatus>,
    /// The query log.
    pub query_log: QueryLogStatus,
    /// This node's cluster, if it is in one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cluster: Option<ClusterStatus>,
    /// DNS over TLS, HTTPS and QUIC, if this node serves them.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub encrypted: Option<EncryptedStatus>,
    /// Whether this node serves its API reference at `/api/docs` (to
    /// loopback clients only).
    #[serde(default)]
    pub api_docs: bool,
    /// What is wrong with this node, in words, such as filtering running
    /// without its store. Empty when all is well.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub problems: Vec<String>,
}

/// The compiled filter.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct FilterStatus {
    /// Rules compiled in.
    pub rules: u64,
    /// Bytes of memory the rules take.
    pub memory_bytes: u64,
}

/// One list.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct ListStatus {
    /// The list's ID.
    pub id: String,
    /// Rules read from it, if it was read.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rules: Option<u64>,
    /// Lines with syntax goethite does not support yet.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub unsupported: Option<u64>,
    /// Lines that are not valid rules.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub invalid: Option<u64>,
    /// Why it could not be read, if it could not.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    /// When a download was last tried.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_attempt: Option<Timestamp>,
    /// When a download last succeeded or found the list unchanged.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_success: Option<Timestamp>,
    /// Why the last download failed, if it did.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub download_error: Option<String>,
}

/// One upstream.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct UpstreamStatus {
    /// Address and port.
    pub address: String,
    /// `udp`, `tcp`, `tls` or `https`.
    pub protocol: String,
    /// False while it is skipped after repeated failures.
    pub healthy: bool,
    /// Failures since it last answered.
    pub consecutive_failures: u32,
}

/// The cache.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct CacheStatus {
    /// Answers in it.
    pub entries: u64,
    /// Lookups answered from it.
    pub hits: u64,
    /// Lookups that were not.
    pub misses: u64,
}

/// How clients reach this node over DNS over TLS, HTTPS and QUIC.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct EncryptedStatus {
    /// The name clients reach it by, such as `dns.example`, if configured:
    /// a client ID goes in front of it, as in `anna-phone.dns.example`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub server_name: Option<String>,
    /// The addresses DNS over TLS is served on.
    pub dot: Vec<String>,
    /// The addresses DNS over HTTPS is served on, at the path `/dns-query`
    /// (or `/dns-query/<client ID>`).
    pub doh: Vec<String>,
    /// The addresses DNS over QUIC is served on.
    pub doq: Vec<String>,
    /// Whether the DNS over HTTPS addresses are also an Oblivious DoH
    /// target (RFC 9230): queries at `/dns-query`, keys at
    /// `/.well-known/odohconfigs`.
    #[serde(default)]
    pub odoh: bool,
}

/// Recursive resolution: from the root servers down, instead of asking
/// upstream resolvers.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct RecursionStatus {
    /// Whether servers are shown only as much of a name as they need
    /// (QNAME minimisation, RFC 9156).
    pub qname_minimisation: bool,
    /// Whether servers are asked over IPv6 too.
    pub ipv6: bool,
    /// Whether answers are validated with DNSSEC.
    #[serde(default)]
    pub dnssec: bool,
    /// Queries sent to authoritative servers since start.
    pub sent: u64,
    /// Of them, over TCP.
    pub tcp: u64,
    /// Queries no server answered in time.
    pub timeouts: u64,
    /// Client queries that could not be resolved (SERVFAIL), bogus ones
    /// included.
    pub failures: u64,
    /// Answers DNSSEC proved authentic (the AD bit).
    #[serde(default)]
    pub secure: u64,
    /// Answers from unsigned zones.
    #[serde(default)]
    pub insecure: u64,
    /// Answers whose signatures or proofs failed, refused with SERVFAIL.
    #[serde(default)]
    pub bogus: u64,
    /// Zone cuts known.
    pub zones: u64,
    /// Authoritative servers with statistics.
    pub servers: u64,
}

/// The query log.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, ToSchema)]
pub struct QueryLogStatus {
    /// Whether queries are logged.
    pub enabled: bool,
    /// Entries in it.
    pub entries: u64,
    /// Entries dropped because the writer could not keep up.
    pub dropped: u64,
}

/// Everything the handlers share.
pub struct Api {
    /// The store.
    pub store: Arc<Store>,
    /// The query log and statistics.
    pub log: Arc<QueryLog>,
    /// The data plane.
    pub control: Arc<dyn Control>,
    /// Settings.
    pub config: ApiConfig,
    /// The sessions this node holds.
    pub(crate) sessions: sessions::Sessions,
    /// Failed sign-ins, per address and per name.
    pub(crate) attempts: login_attempts::Attempts,
}

impl Api {
    /// Everything the handlers share.
    pub fn new(
        store: Arc<Store>,
        log: Arc<QueryLog>,
        control: Arc<dyn Control>,
        config: ApiConfig,
    ) -> Self {
        Self {
            store,
            log,
            control,
            config,
            sessions: sessions::Sessions::default(),
            attempts: login_attempts::Attempts::default(),
        }
    }
}

// Nothing printed: the config carries the TLS server config, private key
// included, and the rest are handles.
impl std::fmt::Debug for Api {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Api").finish_non_exhaustive()
    }
}

/// How long one request may take.
const REQUEST_TIMEOUT: Duration = Duration::from_secs(30);

/// The routes, with authentication, limits and security headers.
pub fn router(api: &Arc<Api>) -> Router {
    // Authentication runs first, then the role check, then forwarding
    // changes to the leader.
    let protected = handlers::routes()
        .merge(users::routes())
        .route("/api/v1/cluster", axum::routing::get(cluster::get_cluster))
        .route(
            "/api/v1/cluster/promote",
            axum::routing::post(cluster::promote),
        )
        .route(
            "/api/v1/cluster/demote",
            axum::routing::post(cluster::demote),
        )
        .route(
            "/api/v1/cluster/members/{node}",
            axum::routing::delete(cluster::remove_member),
        )
        .route_layer(middleware::from_fn_with_state(
            Arc::clone(api),
            cluster::forward_writes,
        ))
        .route_layer(middleware::from_fn(auth::authorize))
        .route_layer(middleware::from_fn_with_state(
            Arc::clone(api),
            auth::authenticate,
        ));
    Router::new()
        .route("/api/v1/health", axum::routing::get(handlers::health))
        .merge(users::public_routes())
        // Off unless configured, and loopback only: see `docs`.
        .route("/api/docs", axum::routing::get(docs::page))
        .route("/api/docs/scalar.js", axum::routing::get(docs::scalar))
        .route("/api/docs/start.js", axum::routing::get(docs::start))
        .route("/api/docs/openapi.json", axum::routing::get(docs::document))
        .merge(protected)
        .fallback(web::serve)
        .with_state(Arc::clone(api))
        .layer(DefaultBodyLimit::max(MAX_BODY))
        .layer(middleware::from_fn_with_state(Arc::clone(api), auth::guard))
        .layer(middleware::from_fn(limit_time))
        .layer(middleware::from_fn(security_headers))
        .layer(middleware::from_fn(span))
}

/// A span for each request, for traces: its method, the route it matched
/// (never the path itself, which may name a client) and its status.
async fn span(request: Request<axum::body::Body>, next: Next) -> Response {
    let route = request
        .extensions()
        .get::<axum::extract::MatchedPath>()
        .map_or("unmatched", |path| path.as_str())
        .to_owned();
    let span = tracing::debug_span!(
        "api",
        method = %request.method(),
        %route,
        status = tracing::field::Empty,
    );
    let response = tracing::Instrument::instrument(next.run(request), span.clone()).await;
    span.record("status", response.status().as_u16());
    response
}

/// Gives up on requests that take too long.
async fn limit_time(request: Request<axum::body::Body>, next: Next) -> Result<Response, ApiError> {
    tokio::time::timeout(REQUEST_TIMEOUT, next.run(request))
        .await
        .map_err(|_| ApiError::internal("the request took too long"))
}

/// Headers every response gets: a strict Content Security Policy, and no
/// framing, sniffing or referrers. Responses are not cached unless they say
/// otherwise (only the web UI's files do). Images may also come from the
/// DNS leak test's names (`*.leak.goethite.test`), which only goethite
/// answers and only with NXDOMAIN: loading them makes the browser look the
/// names up.
async fn security_headers(request: Request<axum::body::Body>, next: Next) -> Response {
    let mut response = next.run(request).await;
    let headers = response.headers_mut();
    // A page may tighten its own policy with a nonce (the API reference).
    headers
        .entry(CONTENT_SECURITY_POLICY)
        .or_insert(HeaderValue::from_static(
            "default-src 'self'; script-src 'self'; style-src 'self'; \
         img-src 'self' data: http://*.leak.goethite.test https://*.leak.goethite.test; \
         font-src 'self'; connect-src 'self'; object-src 'none'; base-uri 'none'; \
         form-action 'self'; frame-ancestors 'none'",
        ));
    for (name, value) in [
        (X_CONTENT_TYPE_OPTIONS, "nosniff"),
        (X_FRAME_OPTIONS, "DENY"),
        (REFERRER_POLICY, "no-referrer"),
    ] {
        headers.insert(name, HeaderValue::from_static(value));
    }
    headers
        .entry(CACHE_CONTROL)
        .or_insert(HeaderValue::from_static("no-store"));
    response
}
