/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The audit log: every change, newest first. */
        get: operations["get_audit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists all clients, oldest first. */
        get: operations["list_clients"];
        put?: never;
        /** Creates a client. */
        post: operations["create_client"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gets one client. */
        get: operations["get_client"];
        /** Replaces a client's spec. */
        put: operations["update_client"];
        post?: never;
        /** Deletes a client. */
        delete: operations["delete_client"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cluster": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * This node's cluster: its role, the other node, and how following the
         *     primary goes.
         */
        get: operations["get_cluster"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cluster/demote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Makes this node a replica: it copies the other node's configuration
         *     from then on, replacing its own. Refused unless the other node is
         *     reachable and primary, unless forced.
         */
        post: operations["demote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cluster/promote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Makes this node the primary. Its configuration becomes the cluster's,
         *     in a new epoch. Refused while the current primary is reachable, unless
         *     forced: demote that one first.
         */
        post: operations["promote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists all groups, oldest first. */
        get: operations["list_groups"];
        put?: never;
        /** Creates a group. */
        post: operations["create_group"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gets one group. */
        get: operations["get_group"];
        /** Replaces a group's spec. */
        put: operations["update_group"];
        post?: never;
        /** Deletes a group. */
        delete: operations["delete_group"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whether the API is up. Needs no token. */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists all filter lists, oldest first. */
        get: operations["list_lists"];
        put?: never;
        /** Creates a filter list. */
        post: operations["create_list"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lists/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Downloads every URL list now, in the background. `GET /api/v1/status`
         *     shows the result.
         */
        post: operations["refresh_lists"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lists/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gets one filter list. */
        get: operations["get_list"];
        /** Replaces a filter list's spec. */
        put: operations["update_list"];
        post?: never;
        /** Deletes a filter list. */
        delete: operations["delete_list"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** This API's OpenAPI document. */
        get: operations["get_openapi"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whether filtering is paused. */
        get: operations["get_pause"];
        /**
         * Pauses filtering for everyone for a while. It resumes by itself, and on a
         *     restart.
         */
        put: operations["put_pause"];
        post?: never;
        /** Resumes filtering. */
        delete: operations["delete_pause"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/querylog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Searches the query log, newest first. A search looks at no more than
         *     100,000 entries; follow `next` to continue.
         */
        get: operations["get_querylog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists all custom rules, oldest first. */
        get: operations["list_rules"];
        put?: never;
        /** Creates a custom rule. */
        post: operations["create_rule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gets one custom rule. */
        get: operations["get_rule"];
        /** Replaces a custom rule's spec. */
        put: operations["update_rule"];
        post?: never;
        /** Deletes a custom rule. */
        delete: operations["delete_rule"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists all schedules, oldest first. */
        get: operations["list_schedules"];
        put?: never;
        /** Creates a schedule. */
        post: operations["create_schedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schedules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gets one schedule. */
        get: operations["get_schedule"];
        /** Replaces a schedule's spec. */
        put: operations["update_schedule"];
        post?: never;
        /** Deletes a schedule. */
        delete: operations["delete_schedule"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The filtering settings. */
        get: operations["get_settings"];
        /** Replaces the filtering settings. */
        put: operations["put_settings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Counts per hour, and the names and clients asked most. */
        get: operations["get_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** How the node is doing: filter, lists, upstreams, cache, query log. */
        get: operations["get_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics in the Prometheus text format. */
        get: operations["get_metrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Who made a change, and from where. */
        Actor: {
            /** @description The client's IP address, for API requests. */
            address?: string | null;
            /** @description What kind of actor. */
            kind: components["schemas"]["ActorKind"];
            /**
             * @description The cluster node the change came from or through, when it was not
             *     made on this node.
             */
            node?: string | null;
        };
        /** @description Who made a change: `token` (an API client with the admin token), `unauthenticated` (an API client on loopback while no admin token is configured), `cli` (the goethite command line), `system` (goethite itself) or `replication` (copied from the cluster's primary). More may be added: show unknown values as they are. */
        ActorKind: string;
        /** @description What an audit entry records: `create`, `update` or `delete` (a resource or the settings), `import` (the config file's `[filter]` table), `pause` or `resume` (filtering), `refresh` (a list download), `replicate` (a copy of the cluster primary's configuration), `promote` or `demote` (this node became the cluster's primary or a replica). More may be added: show unknown values as they are. */
        AuditAction: string;
        /** @description One entry of the audit log. */
        AuditEntry: {
            /** @description What. */
            action: components["schemas"]["AuditAction"];
            /** @description Who. */
            actor: components["schemas"]["Actor"];
            /** @description The resource after the change. */
            after?: Record<string, never> | null;
            /** @description The resource before the change. */
            before?: Record<string, never> | null;
            /** @description More about the change, for people. */
            detail?: string | null;
            /**
             * Format: int64
             * @description Increasing number.
             */
            id: number;
            /** @description The kind of resource, if one changed. */
            kind?: string | null;
            /** @description The resource's ID, if one changed. */
            resource?: string | null;
            /**
             * Format: date-time
             * @description When.
             */
            time: string;
        };
        /**
         * @description How blocked names are answered.
         * @enum {string}
         */
        BlockResponseKind: "null_ip" | "nxdomain" | "refused";
        /** @description The cache. */
        CacheStatus: {
            /**
             * Format: int64
             * @description Answers in it.
             */
            entries: number;
            /**
             * Format: int64
             * @description Lookups answered from it.
             */
            hits: number;
            /**
             * Format: int64
             * @description Lookups that were not.
             */
            misses: number;
        };
        /** @description A stored client. */
        Client: {
            /**
             * Format: date-time
             * @description When it was created.
             */
            created_at: string;
            /** @description The ID, chosen by goethite. */
            id: string;
            /**
             * Format: int64
             * @description Counts updates, starting at 1.
             */
            revision: number;
            /** @description What it is. */
            spec: components["schemas"]["ClientSpec"];
            /**
             * Format: date-time
             * @description When it last changed.
             */
            updated_at: string;
        };
        /** @description A device or network, identified by its addresses. */
        ClientSpec: {
            /**
             * @description IP addresses or networks in CIDR notation, such as `192.168.1.23`
             *     or `192.168.1.0/24`. The longest network containing a query's source
             *     address decides which client asked.
             */
            addresses: string[];
            /** @description Free text. */
            comment?: string;
            /** @description The group's ID. */
            group?: string;
            /** @description Who manages the client. */
            managed_by?: components["schemas"]["ManagedBy"];
            /** @description A name for people. */
            name: string;
        };
        /**
         * @description A node's role in its cluster.
         * @enum {string}
         */
        ClusterRole: "primary" | "replica";
        /** @description This node's cluster. */
        ClusterStatus: {
            /** @description Its configuration's version. */
            config: components["schemas"]["ConfigVersion"];
            /** @description This node's name. */
            node: string;
            /** @description The other node, as last seen. */
            peer: components["schemas"]["PeerStatus"];
            /**
             * @description Things someone should look at, in words, such as both nodes being
             *     primary.
             */
            problems: string[];
            /** @description Its role. */
            role: components["schemas"]["ClusterRole"];
            sync?: components["schemas"]["SyncStatus"] | null;
            /**
             * @description Whether configuration changes can be made through this node now:
             *     on the primary, or on a replica that reaches the primary.
             */
            writable: boolean;
        };
        /**
         * @description Which configuration a store holds.
         *
         *     `epoch` names a line of history: it is chosen at random when a store is
         *     created and again when a node becomes the cluster's primary. `version`
         *     counts the changes along it. A replica takes a configuration whose epoch
         *     differs from its own, or whose version is newer.
         */
        ConfigVersion: {
            /**
             * Format: int64
             * @description The line of history: a random number below 2^53, so it is exact in
             *     JSON.
             */
            epoch: number;
            /**
             * Format: int64
             * @description Changes so far along it.
             */
            version: number;
        };
        /** @description Counts of queries by outcome. */
        Counters: {
            /**
             * Format: int64
             * @description Blocked by the filter.
             */
            blocked: number;
            /**
             * Format: int64
             * @description Answered from the cache.
             */
            cached: number;
            /**
             * Format: int64
             * @description Total time spent resolving, in microseconds; divide by `queries` for
             *     the average.
             */
            elapsed_us: number;
            /**
             * Format: int64
             * @description No upstream answered.
             */
            failed: number;
            /**
             * Format: int64
             * @description Answered by an upstream.
             */
            forwarded: number;
            /**
             * Format: int64
             * @description Answered from goethite's own records.
             */
            local: number;
            /**
             * Format: int64
             * @description All answered queries.
             */
            queries: number;
            /**
             * Format: int64
             * @description Refused or rejected by policy.
             */
            rejected: number;
            /**
             * Format: int64
             * @description Sent to a safe search endpoint.
             */
            safe_search: number;
        };
        /** @description The body of every error response. */
        ErrorBody: {
            /** @description What went wrong. */
            error: components["schemas"]["ErrorDetail"];
        };
        /** @description What went wrong. */
        ErrorDetail: {
            /**
             * @description A stable code: `not_found`, `invalid`, `conflict`,
             *     `revision_mismatch`, `unauthorized`, `forbidden`, `bad_request`,
             *     `unavailable` or `internal`.
             */
            code: string;
            /** @description For people. */
            message: string;
        };
        /** @description The compiled filter. */
        FilterStatus: {
            /**
             * Format: int64
             * @description Bytes of memory the rules take.
             */
            memory_bytes: number;
            /**
             * Format: int64
             * @description Rules compiled in.
             */
            rules: number;
        };
        /** @description A stored group. */
        Group: {
            /**
             * Format: date-time
             * @description When it was created.
             */
            created_at: string;
            /** @description The ID, chosen by goethite. */
            id: string;
            /**
             * Format: int64
             * @description Counts updates, starting at 1.
             */
            revision: number;
            /** @description What it is. */
            spec: components["schemas"]["GroupSpec"];
            /**
             * Format: date-time
             * @description When it last changed.
             */
            updated_at: string;
        };
        /** @description A list a group uses, always or while a schedule is active. */
        GroupList: {
            /** @description The list's ID. */
            list: string;
            /**
             * @description The schedule's ID: the list applies only while the schedule is
             *     active. Without one it always applies.
             */
            schedule?: string | null;
        };
        /** @description A group of clients with the same filtering. */
        GroupSpec: {
            /** @description Free text. */
            comment?: string;
            /** @description Whether the group's clients are filtered at all. */
            filtering?: boolean;
            /**
             * @description The lists the group uses. Custom rules always apply while filtering
             *     is on.
             */
            lists?: components["schemas"]["GroupList"][];
            /** @description Who manages the group. */
            managed_by?: components["schemas"]["ManagedBy"];
            /** @description A name for people. */
            name: string;
            /** @description Whether search engines are sent to their safe endpoints. */
            safe_search?: boolean;
        };
        /** @description The answer to a health check. */
        Health: {
            /** @description Always `ok`. */
            status: string;
        };
        /** @description One hour in a report. */
        HourPoint: {
            /** @description Its counts. */
            counters: components["schemas"]["Counters"];
            /**
             * Format: date-time
             * @description When the hour starts.
             */
            start: string;
        };
        /** @description A stored filter list. */
        List: {
            /**
             * Format: date-time
             * @description When it was created.
             */
            created_at: string;
            /** @description The ID, chosen by goethite. */
            id: string;
            /**
             * Format: int64
             * @description Counts updates, starting at 1.
             */
            revision: number;
            /** @description What it is. */
            spec: components["schemas"]["ListSpec"];
            /**
             * Format: date-time
             * @description When it last changed.
             */
            updated_at: string;
        };
        /** @description A filter list: a file on disk or an `https://` URL. */
        ListSpec: {
            /** @description Free text. */
            comment?: string;
            /** @description Whether the list is used at all. */
            enabled?: boolean;
            /** @description Who manages the list. */
            managed_by?: components["schemas"]["ManagedBy"];
            /** @description A name for people. */
            name: string;
            /** @description The list file: an absolute path on the node. */
            path?: string | null;
            /**
             * @description Where to download the list from: an `https://` URL. Exactly one of
             *     `url` and `path` is set.
             */
            url?: string | null;
        };
        /** @description One list. */
        ListStatus: {
            /** @description Why the last download failed, if it did. */
            download_error?: string | null;
            /** @description Why it could not be read, if it could not. */
            error?: string | null;
            /** @description The list's ID. */
            id: string;
            /**
             * Format: int64
             * @description Lines that are not valid rules.
             */
            invalid?: number | null;
            /**
             * Format: date-time
             * @description When a download was last tried.
             */
            last_attempt?: string | null;
            /**
             * Format: date-time
             * @description When a download last succeeded or found the list unchanged.
             */
            last_success?: string | null;
            /**
             * Format: int64
             * @description Rules read from it, if it was read.
             */
            rules?: number | null;
            /**
             * Format: int64
             * @description Lines with syntax goethite does not support yet.
             */
            unsupported?: number | null;
        };
        /**
         * @description Who manages a resource. Resources managed by Terraform are read-only in
         *     the web UI and the TUI, so they do not drift from their definition.
         * @enum {string}
         */
        ManagedBy: "api" | "terraform" | "config_file";
        /** @description Whether filtering is paused. */
        Pause: {
            /**
             * Format: date-time
             * @description Until when filtering is paused; absent when it is not.
             */
            paused_until?: string | null;
        };
        /** @description How long to pause filtering. */
        PauseRequest: {
            /**
             * Format: int32
             * @description Seconds, from 1 to 604,800 (a week).
             */
            seconds: number;
        };
        /** @description The other node, as last seen. */
        PeerStatus: {
            /** @description Its cluster address. */
            address: string;
            /**
             * Format: date-time
             * @description When it was last checked.
             */
            checked_at?: string | null;
            config?: components["schemas"]["ConfigVersion"] | null;
            /** @description Why the last check failed, if it did. */
            error?: string | null;
            /** @description Its name. */
            node: string;
            /** @description Whether it answered the last check. */
            reachable: boolean;
            role?: components["schemas"]["ClusterRole"] | null;
            /** @description Its goethite version, when last reached. */
            version?: string | null;
        };
        /**
         * @description How a query reached goethite.
         * @enum {string}
         */
        Protocol: "udp" | "tcp";
        /** @description One logged query, as the API shows it. */
        QueryEntry: {
            /** @description The client's address (shortened if the log anonymizes clients). */
            client: string;
            /** @description The known client's ID. */
            client_id?: string | null;
            /** @description For a block through a CNAME, the CNAME target. */
            cname?: string | null;
            /**
             * Format: int32
             * @description How long resolving took, in microseconds.
             */
            elapsed_us: number;
            /** @description The client's group's ID. */
            group?: string | null;
            /**
             * Format: int64
             * @description The entry's ID; entries with lower IDs are older. Use it as the
             *     `before` cursor to page.
             */
            id: number;
            /** @description The rule's list ID, or `custom` for custom rules. */
            list?: string | null;
            /** @description The name asked for. */
            name: string;
            /** @description How the answer came about. */
            outcome: components["schemas"]["QueryOutcome"];
            /** @description How the query arrived. */
            protocol: components["schemas"]["Protocol"];
            /** @description The type asked for, such as `A` or `TYPE65`. */
            qtype: string;
            /** @description The response code, such as `NOERROR`. */
            rcode: string;
            /** @description The filter rule that applied, in AdGuard syntax. */
            rule?: string | null;
            /**
             * Format: date-time
             * @description When the query arrived.
             */
            time: string;
            /** @description For a forwarded answer, the upstream's address. */
            upstream?: string | null;
        };
        /** @description The query log. */
        QueryLogStatus: {
            /**
             * Format: int64
             * @description Entries dropped because the writer could not keep up.
             */
            dropped: number;
            /** @description Whether queries are logged. */
            enabled: boolean;
            /**
             * Format: int64
             * @description Entries in it.
             */
            entries: number;
        };
        /**
         * @description How an answer came about.
         * @enum {string}
         */
        QueryOutcome: "local" | "rejected" | "blocked" | "safe_search" | "cached" | "forwarded" | "failed";
        /** @description A page of search results. */
        QueryPage: {
            /** @description Matching entries, newest first. */
            entries: components["schemas"]["QueryEntry"][];
            /**
             * Format: int64
             * @description Pass as `before` for the next page; absent at the end of the log.
             */
            next?: number | null;
        };
        /** @description How to change a node's role. */
        RoleChange: {
            /**
             * @description Change it even though the other node is reachable and would
             *     disagree, leaving two primaries (or two replicas) until one changes.
             */
            force?: boolean;
        };
        /** @description A stored custom rule. */
        Rule: {
            /**
             * Format: date-time
             * @description When it was created.
             */
            created_at: string;
            /** @description The ID, chosen by goethite. */
            id: string;
            /**
             * Format: int64
             * @description Counts updates, starting at 1.
             */
            revision: number;
            /** @description What it is. */
            spec: components["schemas"]["RuleSpec"];
            /**
             * Format: date-time
             * @description When it last changed.
             */
            updated_at: string;
        };
        /** @description A custom filtering rule, in any syntax the filter lists use. */
        RuleSpec: {
            /** @description Free text. */
            comment?: string;
            /** @description Whether the rule is used. */
            enabled?: boolean;
            /** @description Who manages the rule. */
            managed_by?: components["schemas"]["ManagedBy"];
            /** @description The rule, such as `||ads.example^` or `@@||good.example^`. */
            rule: string;
        };
        /** @description A stored schedule. */
        Schedule: {
            /**
             * Format: date-time
             * @description When it was created.
             */
            created_at: string;
            /** @description The ID, chosen by goethite. */
            id: string;
            /**
             * Format: int64
             * @description Counts updates, starting at 1.
             */
            revision: number;
            /** @description What it is. */
            spec: components["schemas"]["ScheduleSpec"];
            /**
             * Format: date-time
             * @description When it last changed.
             */
            updated_at: string;
        };
        /** @description When something applies: weekly time windows in a time zone. */
        ScheduleSpec: {
            /** @description Free text. */
            comment?: string;
            /** @description Who manages the schedule. */
            managed_by?: components["schemas"]["ManagedBy"];
            /** @description A name for people. */
            name: string;
            /** @description An IANA time zone such as `Europe/Berlin`, or `UTC`. */
            time_zone?: string;
            /** @description The windows. */
            windows: components["schemas"]["Window"][];
        };
        /** @description The settings, with their revision. */
        Settings: {
            /**
             * Format: int64
             * @description Counts updates, starting at 1.
             */
            revision: number;
            /** @description The settings. */
            spec: components["schemas"]["SettingsSpec"];
            /**
             * Format: date-time
             * @description When they last changed.
             */
            updated_at: string;
        };
        /** @description Node-wide filtering settings. */
        SettingsSpec: {
            /** @description How blocked names are answered. */
            block_response?: components["schemas"]["BlockResponseKind"];
            /**
             * Format: int32
             * @description Time to live of null-IP answers, in seconds, at most 86,400.
             */
            blocked_ttl?: number;
            /**
             * Format: int32
             * @description How often downloaded lists are refreshed, in hours, 1 to 168.
             */
            list_update_hours?: number;
            /** @description The master switch: when off, nothing is filtered for anyone. */
            protection?: boolean;
        };
        /** @description Statistics over a time range. */
        StatsReport: {
            /**
             * Format: date-time
             * @description The start of the first hour covered.
             */
            from: string;
            /** @description Counts per hour, oldest first; hours without queries are left out. */
            hours: components["schemas"]["HourPoint"][];
            /**
             * Format: date-time
             * @description When the report was made.
             */
            to: string;
            /** @description The blocked names asked for most. */
            top_blocked: components["schemas"]["TopEntry"][];
            /** @description The clients asking most, by client ID or address. */
            top_clients: components["schemas"]["TopEntry"][];
            /** @description The names asked for most. */
            top_names: components["schemas"]["TopEntry"][];
            /** @description Counts over the whole range. */
            totals: components["schemas"]["Counters"];
        };
        /** @description How the node is doing. */
        Status: {
            cache?: components["schemas"]["CacheStatus"] | null;
            cluster?: components["schemas"]["ClusterStatus"] | null;
            /** @description The compiled filter. */
            filter: components["schemas"]["FilterStatus"];
            /** @description Each list, by ID. */
            lists: components["schemas"]["ListStatus"][];
            /**
             * Format: date-time
             * @description Until when filtering is paused, if it is.
             */
            paused_until?: string | null;
            /** @description Whether filtering is on in the settings. */
            protection: boolean;
            /** @description The query log. */
            query_log: components["schemas"]["QueryLogStatus"];
            /**
             * Format: date-time
             * @description When goethite started.
             */
            started_at: string;
            /** @description The upstreams, in configured order. */
            upstreams: components["schemas"]["UpstreamStatus"][];
            /** @description The running version. */
            version: string;
        };
        /** @description How a replica follows the primary. */
        SyncStatus: {
            /** @description Why the last attempt failed, if it did. */
            error?: string | null;
            /**
             * Format: date-time
             * @description When the primary last answered.
             */
            last_contact?: string | null;
            /**
             * Format: date-time
             * @description When its configuration was last copied.
             */
            last_copy?: string | null;
        };
        /** @description A name or client and how often it was seen. */
        TopEntry: {
            /**
             * Format: int64
             * @description How often, approximately.
             */
            count: number;
            /** @description The name, client ID or client address. */
            key: string;
        };
        /** @description One upstream. */
        UpstreamStatus: {
            /** @description Address and port. */
            address: string;
            /**
             * Format: int32
             * @description Failures since it last answered.
             */
            consecutive_failures: number;
            /** @description False while it is skipped after repeated failures. */
            healthy: boolean;
            /** @description `udp`, `tcp`, `tls` or `https`. */
            protocol: string;
        };
        /**
         * @description A day of the week.
         * @enum {string}
         */
        Weekday: "mon" | "tue" | "wed" | "thu" | "fri" | "sat" | "sun";
        /**
         * @description A weekly time window. `end` before `start` runs past midnight into the
         *     next day.
         */
        Window: {
            /** @description The days the window starts on. */
            days: components["schemas"]["Weekday"][];
            /** @description Local end time, `HH:MM` (`24:00` for midnight). */
            end: string;
            /** @description Local start time, `HH:MM`. */
            start: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_audit: {
        parameters: {
            query?: {
                /** @description Only entries before this ID. */
                before?: number;
                /** @description How many, 1 to 1000 (default 100). */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entries, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEntry"][];
                };
            };
        };
    };
    list_clients: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All of them, oldest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Client"][];
                };
            };
            /** @description No valid admin token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    create_client: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientSpec"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Client"];
                };
            };
            /** @description It refers to something that does not exist */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description It is not valid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_client: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description It, with its revision as the ETag */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Client"];
                };
            };
            /** @description No such ID */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    update_client: {
        parameters: {
            query?: never;
            header?: {
                /** @description The revision the change is based on */
                "If-Match"?: string | null;
            };
            path: {
                /** @description The ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientSpec"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Client"];
                };
            };
            /** @description No such ID */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description It refers to something that does not exist */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description It changed since that revision */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description It is not valid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    delete_client: {
        parameters: {
            query?: never;
            header?: {
                /** @description The revision the deletion is based on */
                "If-Match"?: string | null;
            };
            path: {
                /** @description The ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such ID */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Something still refers to it */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description It changed since that revision */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_cluster: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The cluster */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterStatus"];
                };
            };
            /** @description This node is not in a cluster */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    demote: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleChange"];
            };
        };
        responses: {
            /** @description This node is a replica */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterStatus"];
                };
            };
            /** @description This node is not in a cluster */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The other node is not a reachable primary */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    promote: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleChange"];
            };
        };
        responses: {
            /** @description This node is the primary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterStatus"];
                };
            };
            /** @description This node is not in a cluster */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The other node is reachable and primary */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_groups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All of them, oldest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"][];
                };
            };
            /** @description No valid admin token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    create_group: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupSpec"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
            /** @description It refers to something that does not exist */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description It is not valid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_group: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description It, with its revision as the ETag */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
            /** @description No such ID */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    update_group: {
        parameters: {
            query?: never;
            header?: {
                /** @description The revision the change is based on */
                "If-Match"?: string | null;
            };
            path: {
                /** @description The ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupSpec"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
            /** @description No such ID */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description It refers to something that does not exist */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description It changed since that revision */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description It is not valid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    delete_group: {
        parameters: {
            query?: never;
            header?: {
                /** @description The revision the deletion is based on */
                "If-Match"?: string | null;
            };
            path: {
                /** @description The ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such ID */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Something still refers to it */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description It changed since that revision */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    list_lists: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All of them, oldest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["List"][];
                };
            };
            /** @description No valid admin token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    create_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListSpec"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["List"];
                };
            };
            /** @description It refers to something that does not exist */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description It is not valid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    refresh_lists: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The download started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description It, with its revision as the ETag */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["List"];
                };
            };
            /** @description No such ID */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    update_list: {
        parameters: {
            query?: never;
            header?: {
                /** @description The revision the change is based on */
                "If-Match"?: string | null;
            };
            path: {
                /** @description The ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListSpec"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["List"];
                };
            };
            /** @description No such ID */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description It refers to something that does not exist */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description It changed since that revision */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description It is not valid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    delete_list: {
        parameters: {
            query?: never;
            header?: {
                /** @description The revision the deletion is based on */
                "If-Match"?: string | null;
            };
            path: {
                /** @description The ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such ID */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Something still refers to it */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description It changed since that revision */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_openapi: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The OpenAPI 3.1 document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_pause: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Whether filtering is paused */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pause"];
                };
            };
        };
    };
    put_pause: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PauseRequest"];
            };
        };
        responses: {
            /** @description Paused */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pause"];
                };
            };
            /** @description Not between 1 second and a week */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    delete_pause: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resumed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pause"];
                };
            };
        };
    };
    get_querylog: {
        parameters: {
            query?: {
                /** @description Only entries older than this ID: the `next` of the previous page. */
                before?: number;
                /** @description How many entries, 1 to 1000 (default 100). */
                limit?: number;
                /** @description Only this client address, client ID or group ID. */
                client?: string;
                /** @description Only names containing this text, ignoring case. */
                name?: string;
                /** @description Only this outcome. */
                outcome?: components["schemas"]["QueryOutcome"];
                /** @description Only entries at or after this time (RFC 3339). */
                since?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryPage"];
                };
            };
        };
    };
    list_rules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All of them, oldest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rule"][];
                };
            };
            /** @description No valid admin token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    create_rule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleSpec"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rule"];
                };
            };
            /** @description It refers to something that does not exist */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description It is not valid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_rule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description It, with its revision as the ETag */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rule"];
                };
            };
            /** @description No such ID */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    update_rule: {
        parameters: {
            query?: never;
            header?: {
                /** @description The revision the change is based on */
                "If-Match"?: string | null;
            };
            path: {
                /** @description The ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleSpec"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rule"];
                };
            };
            /** @description No such ID */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description It refers to something that does not exist */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description It changed since that revision */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description It is not valid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    delete_rule: {
        parameters: {
            query?: never;
            header?: {
                /** @description The revision the deletion is based on */
                "If-Match"?: string | null;
            };
            path: {
                /** @description The ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such ID */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Something still refers to it */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description It changed since that revision */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_schedules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All of them, oldest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule"][];
                };
            };
            /** @description No valid admin token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    create_schedule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleSpec"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule"];
                };
            };
            /** @description It refers to something that does not exist */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description It is not valid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_schedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description It, with its revision as the ETag */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule"];
                };
            };
            /** @description No such ID */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    update_schedule: {
        parameters: {
            query?: never;
            header?: {
                /** @description The revision the change is based on */
                "If-Match"?: string | null;
            };
            path: {
                /** @description The ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleSpec"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule"];
                };
            };
            /** @description No such ID */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description It refers to something that does not exist */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description It changed since that revision */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description It is not valid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    delete_schedule: {
        parameters: {
            query?: never;
            header?: {
                /** @description The revision the deletion is based on */
                "If-Match"?: string | null;
            };
            path: {
                /** @description The ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such ID */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Something still refers to it */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description It changed since that revision */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The settings, with their revision as the ETag */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
        };
    };
    put_settings: {
        parameters: {
            query?: never;
            header?: {
                /** @description The revision the change is based on */
                "If-Match"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsSpec"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            /** @description They changed since that revision */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description They are not valid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_stats: {
        parameters: {
            query?: {
                /** @description The last this many hours, 1 to 720 (default 24). */
                hours?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsReport"];
                };
            };
        };
    };
    get_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    get_metrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prometheus text format */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": unknown;
                };
            };
        };
    };
}
