[package]
name = "goethite-cluster"
description = "Cluster support for goethite: replicated config, VRRP floating IP and (later) Raft."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
publish.workspace = true

[lints]
workspace = true
