[package]
name = "goethite-store"
description = "Embedded storage (redb) for goethite query logs, statistics and configuration."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
publish.workspace = true

[lints]
workspace = true
